version: '3.8'
services:
  # TODO vpn-c2 config needs to use socks5 proxy tor
  # TODO vpn-c2 needs to be customized to connect to HTB
  vpn-c2:
    env_file:       .env
    image:           qmcgaw/gluetun
    container_name:  vpn-c2
    ports:
      - "0.0.0.0:51820:51820/udp"
    volumes:
      #- syslog-client:/etc/rsyslog.d:ro
      - vpn-c2-etc:/gluetun/custom.conf.d/:ro
    restart:         always
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    depends_on:
      #syslog:
      #  condition:   service_started
      tor:
        condition:   service_healthy

volumes:
  vpn-c2-etc:

