version: '3.8'
include:
  - pgo/docker-compose.yaml
  #- pg/docker-compose.yaml
  #- pfo/docker-compose.yaml
  #- pf/docker-compose.yaml

volumes:
  aircaps:
    external: true
  airpsks:
    external: true
  wordlists:
    external: true
  #pgo:
  #  external: true

