version: '3.8'
services:
  aircrack-pg-1:
    build: pg/1
    env_file: .env
    #image: innovanon/aircrack-pg-1
    container_name:  aircrack-pg-1
    #ports:
    #  - "0.0.0.0:55432:55432/tcp"
    volumes:
      - aircaps:/var/teamhack/caps:ro
      - ./prof/:/var/teamhack/prof:rw
      - airpsks:/var/teamhack/psks:rw
      - wordlists:/var/teamhack/wordlists:ro
    command: ["-w", "/var/teamhack/wordlists/$TEAMHACK_WORDLIST", "-b", $TEAMHACK_BSSID, "-l", "/var/teamhack/psks/$TEAMHACK_BSSID.psk", "/var/teamhack/caps/bssid/$TEAMHACK_BSSID.cap"]
      #- syslog-client:/etc/rsyslog.d:ro
    #restart:         always
    #network_mode:    service:vpn-s1
    #healthcheck:
    ##  test: ["CMD-SHELL", "exec 3<> /dev/tcp/0.0.0.0/3633 ; cat <&3 ; exec 3<&-"]
    #  test: ["CMD-SHELL", "nslookup hackthebox.com 0.0.0.0"]
    #  interval:     10s
    #  timeout:       3s
    #  retries:       10
    #depends_on:
    #  import_db:
    #    condition: service_started
    #  syslog:
    #    condition: service_started
    #    #condition:   service_healthy
    #networks:
    #  network:
    #    ipv4_address: 10.5.0.9

  aircrack-pg-2:
    build: pg/2
    env_file: .env
    #image: innovanon/aircrack-pg-1
    container_name:  aircrack-pg-2
    #ports:
    #  - "0.0.0.0:55432:55432/tcp"
    volumes:
      - aircaps:/var/teamhack/caps:ro
      - ./prof/:/var/teamhack/prof:ro
      - airpsks:/var/teamhack/psks:rw
      - wordlists:/var/teamhack/wordlists:ro
    command: ["-w", "/var/teamhack/wordlists/$TEAMHACK_WORDLIST", "-b", $TEAMHACK_BSSID, "-l", "/var/teamhack/psks/$TEAMHACK_BSSID.psk", "/var/teamhack/caps/bssid/$TEAMHACK_BSSID.cap"]
      #- syslog-client:/etc/rsyslog.d:ro
    #restart:         always
    #network_mode:    service:vpn-s1
    #healthcheck:
    ##  test: ["CMD-SHELL", "exec 3<> /dev/tcp/0.0.0.0/3633 ; cat <&3 ; exec 3<&-"]
    #  test: ["CMD-SHELL", "nslookup hackthebox.com 0.0.0.0"]
    #  interval:     10s
    #  timeout:       3s
    #  retries:       10
    #depends_on:
    #  import_db:
    #    condition: service_started
    #  syslog:
    #    condition: service_started
    #    #condition:   service_healthy
    #networks:
    #  network:
    #    ipv4_address: 10.5.0.9

volumes:
  aircaps:
    external: true
  airpsks:
    external: true
  wordlists:
    external: true

