version: '3.8'
#include: 
#  - ../pgrsyslog-client/docker-compose.yaml
services:
  postgres:
    env_file: .env
    image:           postgres
    container_name:  postgres
    ports:
      - "0.0.0.0:5432:5432"
    #environment:
    #  - POSTGRES_USER=root
    #  - POSTGRES_PASSWORD=69novass
    #  - POSTGRES_DB=ldapsql
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
      - syslog-client:/etc/rsyslog.d:ro
    restart:         always
    #network_mode:    service:vpn-s1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ldapsql -U root"]
      interval:     10s
      timeout:       5s
      retries:       10
    #depends_on:
    #  condition: service_started

volumes:
  pgdata:

