version: '3.8'
services:
  vpn-c1:
    env_file:       .env
    image:           qmcgaw/gluetun
    container_name:  vpn-c1
    ports:
      #- "0.0.0.0:9001:9001"
      #- "0.0.0.0:9030:9030"
      - "0.0.0.0:9050:9050"
      - "0.0.0.0:9150:9150"
      #- "0.0.0.0:9051:9051"
      # TODO
      #- "0.0.0.0:51820:51820/udp"
    #volumes:
    #  - syslog-client:/etc/rsyslog.d:ro
    restart:         always
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"

